// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentClient creates a new instance of MockPaymentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPaymentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPaymentClient is an autogenerated mock type for the PaymentClient type
type MockPaymentClient struct {
	mock.Mock
}

type MockPaymentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentClient) EXPECT() *MockPaymentClient_Expecter {
	return &MockPaymentClient_Expecter{mock: &_m.Mock}
}

// Pay provides a mock function for the type MockPaymentClient
func (_mock *MockPaymentClient) Pay(ctx context.Context, orderID uuid.UUID, userID uuid.UUID, paymentMethod string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, orderID, userID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, orderID, userID, paymentMethod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, orderID, userID, paymentMethod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, orderID, userID, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentClient_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type MockPaymentClient_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
//   - userID uuid.UUID
//   - paymentMethod string
func (_e *MockPaymentClient_Expecter) Pay(ctx any, orderID any, userID any, paymentMethod any) *MockPaymentClient_Pay_Call {
	return &MockPaymentClient_Pay_Call{Call: _e.mock.On("Pay", ctx, orderID, userID, paymentMethod)}
}

func (_c *MockPaymentClient_Pay_Call) Run(run func(ctx context.Context, orderID uuid.UUID, userID uuid.UUID, paymentMethod string)) *MockPaymentClient_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPaymentClient_Pay_Call) Return(uUID uuid.UUID, err error) *MockPaymentClient_Pay_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockPaymentClient_Pay_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID, userID uuid.UUID, paymentMethod string) (uuid.UUID, error)) *MockPaymentClient_Pay_Call {
	_c.Call.Return(run)
	return _c
}
