// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function for the type MockService
func (_mock *MockService) PayOrder(ctx context.Context, orderID uuid.UUID, userID uuid.UUID, payMethod string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, orderID, userID, payMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, orderID, userID, payMethod)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, orderID, userID, payMethod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, orderID, userID, payMethod)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type MockService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
//   - userID uuid.UUID
//   - payMethod string
func (_e *MockService_Expecter) PayOrder(ctx any, orderID any, userID any, payMethod any) *MockService_PayOrder_Call {
	return &MockService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, orderID, userID, payMethod)}
}

func (_c *MockService_PayOrder_Call) Run(run func(ctx context.Context, orderID uuid.UUID, userID uuid.UUID, payMethod string)) *MockService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_PayOrder_Call) Return(uUID uuid.UUID, err error) *MockService_PayOrder_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockService_PayOrder_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID, userID uuid.UUID, payMethod string) (uuid.UUID, error)) *MockService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
