// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/DoomGuy1818/rocket-science/inventory/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInventoryService creates a new instance of MockInventoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInventoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockInventoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockInventoryService is an autogenerated mock type for the InventoryService type
type MockInventoryService struct {
	mock.Mock
}

type MockInventoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryService) EXPECT() *MockInventoryService_Expecter {
	return &MockInventoryService_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockInventoryService
func (_mock *MockInventoryService) GetByID(ctx context.Context, ID uuid.UUID) (model.Part, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Part, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Part); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Get(0).(model.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInventoryService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockInventoryService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *MockInventoryService_Expecter) GetByID(ctx any, ID any) *MockInventoryService_GetByID_Call {
	return &MockInventoryService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, ID)}
}

func (_c *MockInventoryService_GetByID_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *MockInventoryService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryService_GetByID_Call) Return(part model.Part, err error) *MockInventoryService_GetByID_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *MockInventoryService_GetByID_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) (model.Part, error)) *MockInventoryService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByFilters provides a mock function for the type MockInventoryService
func (_mock *MockInventoryService) ListByFilters(ctx context.Context, filter *model.PartsFilter) []model.Part {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListByFilters")
	}

	var r0 []model.Part
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.PartsFilter) []model.Part); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}
	return r0
}

// MockInventoryService_ListByFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByFilters'
type MockInventoryService_ListByFilters_Call struct {
	*mock.Call
}

// ListByFilters is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *model.PartsFilter
func (_e *MockInventoryService_Expecter) ListByFilters(ctx any, filter any) *MockInventoryService_ListByFilters_Call {
	return &MockInventoryService_ListByFilters_Call{Call: _e.mock.On("ListByFilters", ctx, filter)}
}

func (_c *MockInventoryService_ListByFilters_Call) Run(run func(ctx context.Context, filter *model.PartsFilter)) *MockInventoryService_ListByFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.PartsFilter
		if args[1] != nil {
			arg1 = args[1].(*model.PartsFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInventoryService_ListByFilters_Call) Return(parts []model.Part) *MockInventoryService_ListByFilters_Call {
	_c.Call.Return(parts)
	return _c
}

func (_c *MockInventoryService_ListByFilters_Call) RunAndReturn(run func(ctx context.Context, filter *model.PartsFilter) []model.Part) *MockInventoryService_ListByFilters_Call {
	_c.Call.Return(run)
	return _c
}
