// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/DoomGuy1818/rocket-science/order/internal/repository/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockRepository
func (_mock *MockRepository) Cancel(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockRepository_Expecter) Cancel(ctx any, orderID any) *MockRepository_Cancel_Call {
	return &MockRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, orderID)}
}

func (_c *MockRepository_Cancel_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Cancel_Call) Return(err error) *MockRepository_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Cancel_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, userID uuid.UUID, parts []uuid.UUID, totalPrice float64) (uuid.UUID, float64, error) {
	ret := _mock.Called(ctx, userID, parts, totalPrice)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 float64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID, float64) (uuid.UUID, float64, error)); ok {
		return returnFunc(ctx, userID, parts, totalPrice)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID, float64) uuid.UUID); ok {
		r0 = returnFunc(ctx, userID, parts, totalPrice)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []uuid.UUID, float64) float64); ok {
		r1 = returnFunc(ctx, userID, parts, totalPrice)
	} else {
		r1 = ret.Get(1).(float64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, []uuid.UUID, float64) error); ok {
		r2 = returnFunc(ctx, userID, parts, totalPrice)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - parts []uuid.UUID
//   - totalPrice float64
func (_e *MockRepository_Expecter) Create(ctx any, userID any, parts any, totalPrice any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, parts, totalPrice)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, userID uuid.UUID, parts []uuid.UUID, totalPrice float64)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []uuid.UUID
		if args[2] != nil {
			arg2 = args[2].([]uuid.UUID)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(uUID uuid.UUID, f float64, err error) *MockRepository_Create_Call {
	_c.Call.Return(uUID, f, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, parts []uuid.UUID, totalPrice float64) (uuid.UUID, float64, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRepository
func (_mock *MockRepository) Get(ctx context.Context, orderID uuid.UUID) (model.Order, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Order, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockRepository_Expecter) Get(ctx any, orderID any) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, orderID)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(order model.Order, err error) *MockRepository_Get_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (model.Order, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Pay provides a mock function for the type MockRepository
func (_mock *MockRepository) Pay(ctx context.Context, orderID uuid.UUID, transactionID uuid.UUID, paymentMethod string) error {
	ret := _mock.Called(ctx, orderID, transactionID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for Pay")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, orderID, transactionID, paymentMethod)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Pay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pay'
type MockRepository_Pay_Call struct {
	*mock.Call
}

// Pay is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
//   - transactionID uuid.UUID
//   - paymentMethod string
func (_e *MockRepository_Expecter) Pay(ctx any, orderID any, transactionID any, paymentMethod any) *MockRepository_Pay_Call {
	return &MockRepository_Pay_Call{Call: _e.mock.On("Pay", ctx, orderID, transactionID, paymentMethod)}
}

func (_c *MockRepository_Pay_Call) Run(run func(ctx context.Context, orderID uuid.UUID, transactionID uuid.UUID, paymentMethod string)) *MockRepository_Pay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_Pay_Call) Return(err error) *MockRepository_Pay_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Pay_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID, transactionID uuid.UUID, paymentMethod string) error) *MockRepository_Pay_Call {
	_c.Call.Return(run)
	return _c
}
