// Code generated by ogen, DO NOT EDIT.
package order_v1

type CancelOrderByIDRes interface {
	cancelOrderByIDRes()
}

type CreateOrderByIDRes interface {
	createOrderByIDRes()
}

type CreateOrderPaymentByIDRes interface {
	createOrderPaymentByIDRes()
}

type GetOrderByIDRes interface {
	getOrderByIDRes()
}
