// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelOrderByID implements CancelOrderByID operation.
//
// Cancel unpaid order for specified ID. If order paid returns error 409.
//
// POST /api/v1/orders/{order_id}/cancel
func (UnimplementedHandler) CancelOrderByID(ctx context.Context, params CancelOrderByIDParams) (r CancelOrderByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrderByID implements CreateOrderByID operation.
//
// Create orders.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrderByID(ctx context.Context, req *OrderCreateRequest) (r CreateOrderByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrderPaymentByID implements CreateOrderPaymentByID operation.
//
// Creates payment for order by ID.
//
// POST /api/v1/orders/{order_id}/pay
func (UnimplementedHandler) CreateOrderPaymentByID(ctx context.Context, req *OrderPaymentRequest, params CreateOrderPaymentByIDParams) (r CreateOrderPaymentByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderByID implements GetOrderByID operation.
//
// Get order data by order's uuid.
//
// GET /api/v1/orders/{order_id}
func (UnimplementedHandler) GetOrderByID(ctx context.Context, params GetOrderByIDParams) (r GetOrderByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
