// Code generated by ogen, DO NOT EDIT.

package order_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelOrderByIDOperation        OperationName = "CancelOrderByID"
	CreateOrderByIDOperation        OperationName = "CreateOrderByID"
	CreateOrderPaymentByIDOperation OperationName = "CreateOrderPaymentByID"
	GetOrderByIDOperation           OperationName = "GetOrderByID"
)
