// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrderByID implements CancelOrderByID operation.
	//
	// Cancel unpaid order for specified ID. If order paid returns error 409.
	//
	// POST /api/v1/orders/{order_id}/cancel
	CancelOrderByID(ctx context.Context, params CancelOrderByIDParams) (CancelOrderByIDRes, error)
	// CreateOrderByID implements CreateOrderByID operation.
	//
	// Create orders.
	//
	// POST /api/v1/orders
	CreateOrderByID(ctx context.Context, req *OrderCreateRequest) (CreateOrderByIDRes, error)
	// CreateOrderPaymentByID implements CreateOrderPaymentByID operation.
	//
	// Creates payment for order by ID.
	//
	// POST /api/v1/orders/{order_id}/pay
	CreateOrderPaymentByID(ctx context.Context, req *OrderPaymentRequest, params CreateOrderPaymentByIDParams) (CreateOrderPaymentByIDRes, error)
	// GetOrderByID implements GetOrderByID operation.
	//
	// Get order data by order's uuid.
	//
	// GET /api/v1/orders/{order_id}
	GetOrderByID(ctx context.Context, params GetOrderByIDParams) (GetOrderByIDRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
