// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// CancelOrderByIDParams is parameters of CancelOrderByID operation.
type CancelOrderByIDParams struct {
	// Specified ID for order.
	OrderID uuid.UUID
}

func unpackCancelOrderByIDParams(packed middleware.Parameters) (params CancelOrderByIDParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_id",
			In:   "path",
		}
		params.OrderID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeCancelOrderByIDParams(args [1]string, argsEscaped bool, r *http.Request) (params CancelOrderByIDParams, _ error) {
	// Decode path: order_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CreateOrderPaymentByIDParams is parameters of CreateOrderPaymentByID operation.
type CreateOrderPaymentByIDParams struct {
	// Specified ID for order.
	OrderID uuid.UUID
}

func unpackCreateOrderPaymentByIDParams(packed middleware.Parameters) (params CreateOrderPaymentByIDParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_id",
			In:   "path",
		}
		params.OrderID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeCreateOrderPaymentByIDParams(args [1]string, argsEscaped bool, r *http.Request) (params CreateOrderPaymentByIDParams, _ error) {
	// Decode path: order_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetOrderByIDParams is parameters of GetOrderByID operation.
type GetOrderByIDParams struct {
	// Specified ID for order.
	OrderID uuid.UUID
}

func unpackGetOrderByIDParams(packed middleware.Parameters) (params GetOrderByIDParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_id",
			In:   "path",
		}
		params.OrderID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetOrderByIDParams(args [1]string, argsEscaped bool, r *http.Request) (params GetOrderByIDParams, _ error) {
	// Decode path: order_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
